version: '3.3'

services:

    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: ${PROJECT_NAME}-backend
        entrypoint: /usr/src/app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - ./docker/:/usr/src/app/docker/
            - ./backend/:/usr/src/app/backend/
        env_file:
            - ./.env

    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - ${HOST_PORT}:80
        volumes:
            - ./docker/nginx/development/:/etc/nginx/conf.d/
        depends_on:
            - backend

