# Generated by Django 4.0.4 on 2022-07-11 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Код цвета'),
        ),
    ]
