# Generated by Django 4.0.3 on 2022-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
