# Generated by Django 4.0.4 on 2022-07-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_link_name_alter_link_url_alter_social_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='link',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='settings.settings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.URLField(max_length=256, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.TextField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='social',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='socials', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='social',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='settings.settings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(max_length=256, verbose_name='Ссылка'),
        ),
    ]
